# Generated by Django 2.1 on 2018-12-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('abbr', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'specialization',
                'managed': False,
            },
        ),
    ]
