# Generated by Django 2.1.2 on 2019-01-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'registered_mode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegularCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=9)),
                ('course_mode', models.IntegerField()),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'regular_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_modified_on', models.DateTimeField()),
                ('results_publish', models.IntegerField()),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StructureSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'structure_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.CharField(blank=True, db_column='COL 1', max_length=37, null=True)),
                ('col_2', models.CharField(blank=True, db_column='COL 2', max_length=7, null=True)),
                ('col_3', models.CharField(blank=True, db_column='COL 3', max_length=7, null=True)),
                ('col_4', models.CharField(blank=True, db_column='COL 4', max_length=39, null=True)),
                ('col_5', models.CharField(blank=True, db_column='COL 5', max_length=14, null=True)),
                ('col_6', models.CharField(blank=True, db_column='COL 6', max_length=8, null=True)),
                ('cid', models.CharField(blank=True, max_length=6, null=True)),
                ('cname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'timestamp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimestampSession9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'timestamp_session_9',
                'managed': False,
            },
        ),
    ]
