# Generated by Django 2.1.2 on 2019-01-21 16:15

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, db_column='Sl. No', null=True)),
                ('regno', models.IntegerField(blank=True, db_column='regNo', null=True)),
                ('rollno', models.IntegerField(blank=True, db_column='rollNo', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=31, null=True)),
            ],
            options={
                'db_table': 'Bio-tech',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(blank=True, db_column='Sl. No', max_length=27, null=True)),
                ('regno', models.CharField(blank=True, db_column='regNo', max_length=6, null=True)),
                ('rollno', models.CharField(blank=True, db_column='rollNo', max_length=7, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=41, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=7, null=True)),
            ],
            options={
                'db_table': 'CE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, db_column='Sl. No', null=True)),
                ('regno', models.IntegerField(blank=True, db_column='regNo', null=True)),
                ('rollno', models.IntegerField(blank=True, db_column='rollNo', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=35, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Chemical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CiSessions',
            fields=[
                ('session_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.CharField(max_length=120)),
                ('last_activity', models.PositiveIntegerField()),
                ('user_data', models.TextField()),
            ],
            options={
                'db_table': 'ci_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CouncilCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'council_credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, db_column='Sl. No', null=True)),
                ('regno', models.IntegerField(blank=True, db_column='regNo', null=True)),
                ('rollno', models.IntegerField(blank=True, db_column='rollNo', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=34, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=1, null=True)),
            ],
            options={
                'db_table': 'CSE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, db_column='Sl. No', null=True)),
                ('regno', models.IntegerField(blank=True, db_column='regNo', null=True)),
                ('rollno', models.IntegerField(blank=True, db_column='rollNo', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=31, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ECE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, db_column='Sl. No', null=True)),
                ('regno', models.IntegerField(blank=True, db_column='regNo', null=True)),
                ('rollno', models.IntegerField(blank=True, db_column='rollNo', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=39, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=1, null=True)),
            ],
            options={
                'db_table': 'EE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeeRem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=100)),
                ('acc', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'fee_rem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FirstYears',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('roll_number', models.IntegerField(blank=True, db_column='Roll_Number', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=42, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=6, null=True)),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=39, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=1, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, db_column='Mobile_number', null=True)),
                ('email_id', models.CharField(blank=True, db_column='Email_id', max_length=35, null=True)),
            ],
            options={
                'db_table': 'first_years',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_desc', models.TextField()),
            ],
            options={
                'db_table': 'lan_radio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanRadioIp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=48)),
                ('port', models.CharField(max_length=4)),
                ('stream', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'lan_radio_ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('login', models.CharField(max_length=100)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_attempts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Macs',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'macs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mail2017',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('reg', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('terms_accepted', models.IntegerField()),
            ],
            options={
                'db_table': 'mail_2017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailAll',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mail_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(blank=True, max_length=11, null=True)),
                ('email_id', models.CharField(blank=True, max_length=36, null=True)),
                ('first_name', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name', models.CharField(blank=True, max_length=29, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=11, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=13, null=True)),
                ('secondary_email', models.CharField(blank=True, max_length=43, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('department', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=13, null=True)),
                ('password', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'mail_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, db_column='Sl. No', null=True)),
                ('regno', models.IntegerField(blank=True, db_column='regNo', null=True)),
                ('rollno', models.IntegerField(blank=True, db_column='rollNo', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=48, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(blank=True, max_length=8, null=True)),
                ('from_field', models.CharField(blank=True, db_column='from', max_length=16, null=True)),
                ('to', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'mess_change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, db_column='Sl. No', null=True)),
                ('regno', models.IntegerField(blank=True, db_column='regNo', null=True)),
                ('rollno', models.IntegerField(blank=True, db_column='rollNo', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=36, null=True)),
            ],
            options={
                'db_table': 'MME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MtechFirstYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, db_column='Reg No', max_length=7, null=True)),
                ('roll_number', models.CharField(blank=True, db_column='Roll_number', max_length=8, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=33, null=True)),
                ('father_name', models.CharField(blank=True, db_column='Father Name', max_length=27, null=True)),
                ('mother_name', models.CharField(blank=True, db_column='Mother Name', max_length=28, null=True)),
                ('course', models.CharField(blank=True, db_column='Course', max_length=7, null=True)),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=39, null=True)),
                ('gate_score', models.IntegerField(blank=True, db_column='Gate Score', null=True)),
                ('aadhar_number', models.BigIntegerField(blank=True, db_column='Aadhar Number', null=True)),
                ('religion', models.CharField(blank=True, db_column='Religion', max_length=9, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=7, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=1, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, db_column='Mobile_number', null=True)),
                ('email_id', models.CharField(blank=True, db_column='Email_id', max_length=35, null=True)),
                ('date_of_adm_field', models.CharField(blank=True, db_column='Date of Adm.', max_length=9, null=True)),
                ('blood_group', models.CharField(blank=True, db_column='Blood Group', max_length=5, null=True)),
                ('dob', models.CharField(blank=True, db_column='DOB', max_length=10, null=True)),
                ('father_mobile_no', models.BigIntegerField(blank=True, db_column='Father Mobile No', null=True)),
            ],
            options={
                'db_table': 'mtech_first_years',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MtechNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(blank=True, db_column='rollNo', max_length=7, null=True)),
                ('regno', models.CharField(blank=True, db_column='regNo', max_length=15, null=True)),
                ('c', models.CharField(blank=True, db_column='C', max_length=37, null=True)),
                ('d', models.CharField(blank=True, db_column='D', max_length=39, null=True)),
                ('e', models.CharField(blank=True, db_column='E', max_length=22, null=True)),
            ],
            options={
                'db_table': 'mtech_new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Office365',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'office365',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('roll_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('current_section', models.CharField(max_length=4)),
                ('current_year', models.CharField(max_length=4)),
                ('joining_year', models.CharField(max_length=4)),
                ('course', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('birthday', models.DateField()),
                ('country', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=16)),
                ('emergency_contact', models.CharField(max_length=16)),
                ('sbh_account', models.CharField(blank=True, max_length=32, null=True)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
                ('hostel_room', models.CharField(max_length=10)),
                ('hostel', models.CharField(max_length=10)),
                ('mess', models.CharField(max_length=10)),
                ('created_location', models.CharField(max_length=32)),
                ('created_time', models.DateTimeField()),
                ('guardian1', models.CharField(blank=True, max_length=64, null=True)),
                ('relationship1', models.CharField(blank=True, max_length=64, null=True)),
                ('email1', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile1', models.CharField(blank=True, max_length=16, null=True)),
                ('guardian2', models.CharField(blank=True, max_length=64, null=True)),
                ('relationship2', models.CharField(blank=True, max_length=64, null=True)),
                ('email2', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=16, null=True)),
                ('homenumber', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=5, null=True)),
                ('adhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('mac', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'student_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, max_length=7, null=True)),
                ('reg', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tzcodes',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15)),
                ('isused', models.IntegerField(db_column='isUsed')),
            ],
            options={
                'db_table': 'tzCodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_edited', models.IntegerField()),
                ('salt', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('activation_code', models.CharField(blank=True, max_length=40, null=True)),
                ('forgotten_password_code', models.CharField(blank=True, max_length=40, null=True)),
                ('forgotten_password_time', models.PositiveIntegerField(blank=True, null=True)),
                ('remember_code', models.CharField(blank=True, max_length=40, null=True)),
                ('created_on', models.PositiveIntegerField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('active', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
