# Generated by Django 2.1.2 on 2018-12-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]

