# Generated by Django 2.1.2 on 2019-01-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0003_auto_20181225_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
